/**
 * HumanGUI.java
 *
 * Created on 24 October 2007, 11:34
 *
 * @author Simon Archer (archers5)
 */
public class HumanGUI extends javax.swing.JFrame {
    
  // Instance variable to store the Game.
  private Game game;
  
  /**
   * Creates new form HumanGUI
   */
    public HumanGUI() {
      // Create the Game.
      game = new Game(new Player(new Rand()), new Player(new TitForTat()));
      
      this.setTitle("Simulating Evolution");
      
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    payoff1Text = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    payoff2Text = new javax.swing.JTextField();
    action = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    file = new javax.swing.JMenu();
    newGame = new javax.swing.JMenuItem();
    quit = new javax.swing.JMenuItem();
    help = new javax.swing.JMenu();
    about = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    jButton1.setText("Cooperate");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cooperateActionPerformed(evt);
      }
    });

    jButton2.setText("Defect");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        defectActionPerformed(evt);
      }
    });

    jLabel1.setText("Your Payoff");

    payoff1Text.setText("0");

    jLabel2.setText("Opponent's Payoff");

    payoff2Text.setText("0");

    action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    action.setText("[Not Started]");

    file.setText("File");
    newGame.setText("New Game");
    newGame.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        newGameActionPerformed(evt);
      }
    });

    file.add(newGame);

    quit.setText("Quit");
    quit.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        quitActionPerformed(evt);
      }
    });

    file.add(quit);

    jMenuBar1.add(file);

    help.setText("Help");
    help.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        helpActionPerformed(evt);
      }
    });

    about.setText("About");
    about.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        aboutActionPerformed(evt);
      }
    });

    help.add(about);

    jMenuBar1.add(help);

    setJMenuBar(jMenuBar1);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(action, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
          .add(layout.createSequentialGroup()
            .add(12, 12, 12)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
              .add(jLabel1)
              .add(jLabel2))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(payoff2Text)
              .add(payoff1Text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
          .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jButton2)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButton1)
        .add(15, 15, 15)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(payoff1Text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(14, 14, 14)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(payoff2Text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
        .add(action)
        .addContainerGap())
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void quitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitActionPerformed
  {//GEN-HEADEREND:event_quitActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_quitActionPerformed

  private void aboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutActionPerformed
  {//GEN-HEADEREND:event_aboutActionPerformed
    // TODO add your handling code here:
    new About().setVisible(true);
  }//GEN-LAST:event_aboutActionPerformed

  private void newGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newGameActionPerformed
  {//GEN-HEADEREND:event_newGameActionPerformed
    // TODO add your handling code here:
    // Simply create new instances of the game.
    game = new Game(new Player(new Rand()), new Player(new TitForTat()));
    
    // Update the display.
    payoff1Text.setText("0");
    payoff2Text.setText("0");
    
    // Update the display.
    action.setText("[Not Started]");
  }//GEN-LAST:event_newGameActionPerformed

  private void helpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_helpActionPerformed
  {//GEN-HEADEREND:event_helpActionPerformed
// TODO add your handling code here:
  }//GEN-LAST:event_helpActionPerformed

  private void cooperateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cooperateActionPerformed
  {//GEN-HEADEREND:event_cooperateActionPerformed
    // TODO add your handling code here:
    // Invoke the game.
    int strat = game.playPrisoner(Strategy.COOPERATE);
    // Update the payoffs.
    payoff1Text.setText("" + game.getPlayer1().getPayoff());
    payoff2Text.setText("" + game.getPlayer2().getPayoff());
    
    // Update the display.
    if(strat == Strategy.COOPERATE)
      action.setText("The other player co-operates");
    else
      action.setText("The other player defects");
  }//GEN-LAST:event_cooperateActionPerformed

  private void defectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_defectActionPerformed
  {//GEN-HEADEREND:event_defectActionPerformed
    // TODO add your handling code here:
    // Invoke the game.
    int strat = game.playPrisoner(Strategy.DEFECT);
    // Update the payoffs.
    payoff1Text.setText("" + game.getPlayer1().getPayoff());
    payoff2Text.setText("" + game.getPlayer2().getPayoff());
    
    // Update the display.
    if(strat == Strategy.COOPERATE)
      action.setText("The other player co-operates");
    else
      action.setText("The other player defects");
  }//GEN-LAST:event_defectActionPerformed
    
    /**
     * Display the GUI.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {              
                new HumanGUI().setVisible(true);
            }
        });
    }
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem about;
  private javax.swing.JLabel action;
  private javax.swing.JMenu file;
  private javax.swing.JMenu help;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem newGame;
  private javax.swing.JTextField payoff1Text;
  private javax.swing.JTextField payoff2Text;
  private javax.swing.JMenuItem quit;
  // End of variables declaration//GEN-END:variables
    
}
