import java.awt.image.BufferedImage;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map.Entry;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFrame;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.statistics.HistogramDataset;

/**
 * EvolutionGUI.java
 *
 * Created on 24 October 2007, 11:34
 *
 * @author Simon Archer (archers5)
 */
public class EvolutionGUI extends javax.swing.JFrame implements TerritoryGUI
{
  // Store the generation.
  private int generation = 0;
  // Territory size.
  private int size = 3;
  // Selected Player.
  private Player selectedPlayer;
  private int row, column;
  // No neighbours.
  boolean fourNeighbours = true;
  
  private int resultInterval = 50;
  private boolean collectResults = false;
  
  // The arrays for the top performing Probabilistic Strategies.
  Probabilistic [] probs;
  int [] quants;
  
  /**
   * Creates new form EvolutionGUI
   */
  public EvolutionGUI()
  {
    this.setTitle("Simulating Evolution");
    
    initComponents();
  } // EvolutionGUI
    
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    neighbourButtonGroup = new javax.swing.ButtonGroup();
    step = new javax.swing.JButton();
    territoryGrid = territoryGrid = new TerritoryGrid(size);
    generationLabel = new javax.swing.JLabel();
    variablePanel = new javax.swing.JPanel();
    wLabel = new javax.swing.JLabel();
    playerPanel = new javax.swing.JPanel();
    playerPayoff = new javax.swing.JLabel();
    playerPayoffField = new javax.swing.JTextField();
    stratLabel = new javax.swing.JLabel();
    stratCombo = stratCombo = new javax.swing.JComboBox(Game.getStrategies());
    sizeLabel = new javax.swing.JLabel();
    neighbourPanel = new javax.swing.JPanel();
    fourNeighRadioButton = new javax.swing.JRadioButton();
    eightNeighRadioButton = new javax.swing.JRadioButton();
    sizeLabel2 = new javax.swing.JLabel();
    sizeSlider = new javax.swing.JSlider();
    wLabel2 = new javax.swing.JLabel();
    wSlider = new javax.swing.JSlider();
    probabilisticPanel = new javax.swing.JPanel();
    p1Label = new javax.swing.JLabel();
    p2Label = new javax.swing.JLabel();
    p3Label = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    p1ValueLabel = new javax.swing.JLabel();
    p2ValueLabel = new javax.swing.JLabel();
    p3ValueLabel = new javax.swing.JLabel();
    p4ValueLabel = new javax.swing.JLabel();
    runButton = new javax.swing.JButton();
    speedLabel = new javax.swing.JLabel();
    speedSlider = new javax.swing.JSlider();
    speedLabel2 = new javax.swing.JLabel();
    resultsLabel = new javax.swing.JLabel();
    resultsCheckBox = new javax.swing.JCheckBox();
    resultsSlider = new javax.swing.JSlider();
    jMenuBar1 = new javax.swing.JMenuBar();
    file = new javax.swing.JMenu();
    newGame = new javax.swing.JMenuItem();
    quit = new javax.swing.JMenuItem();
    help = new javax.swing.JMenu();
    about = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    step.setText("Step");
    step.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        stepActionPerformed(evt);
      }
    });

    generationLabel.setText("Generation 0");

    wLabel.setText("w Value:");

    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
    playerPayoff.setText("Payoff");

    playerPayoffField.setEditable(false);

    stratLabel.setText("Strategy");

    stratCombo.setEnabled(false);
    stratCombo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        stratComboActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout playerPanelLayout = new org.jdesktop.layout.GroupLayout(playerPanel);
    playerPanel.setLayout(playerPanelLayout);
    playerPanelLayout.setHorizontalGroup(
      playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(playerPanelLayout.createSequentialGroup()
        .add(playerPayoff)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(playerPayoffField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
      .add(playerPanelLayout.createSequentialGroup()
        .add(stratLabel)
        .addContainerGap())
      .add(org.jdesktop.layout.GroupLayout.TRAILING, stratCombo, 0, 144, Short.MAX_VALUE)
    );
    playerPanelLayout.setVerticalGroup(
      playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(playerPanelLayout.createSequentialGroup()
        .add(playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(playerPayoff)
          .add(playerPayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stratLabel)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stratCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );

    sizeLabel.setText("Size:");

    neighbourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Neighbour System"));
    neighbourButtonGroup.add(fourNeighRadioButton);
    fourNeighRadioButton.setSelected(true);
    fourNeighRadioButton.setText("4 Neighbours");
    fourNeighRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    fourNeighRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    fourNeighRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        fourNeighRadioButtonActionPerformed(evt);
      }
    });

    neighbourButtonGroup.add(eightNeighRadioButton);
    eightNeighRadioButton.setText("8 Neighbours");
    eightNeighRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    eightNeighRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    eightNeighRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        eightNeighRadioButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout neighbourPanelLayout = new org.jdesktop.layout.GroupLayout(neighbourPanel);
    neighbourPanel.setLayout(neighbourPanelLayout);
    neighbourPanelLayout.setHorizontalGroup(
      neighbourPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(neighbourPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(neighbourPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(fourNeighRadioButton)
          .add(eightNeighRadioButton))
        .addContainerGap(53, Short.MAX_VALUE))
    );
    neighbourPanelLayout.setVerticalGroup(
      neighbourPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(neighbourPanelLayout.createSequentialGroup()
        .add(fourNeighRadioButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(eightNeighRadioButton))
    );

    sizeLabel2.setText("3");

    sizeSlider.setMaximum(75);
    sizeSlider.setMinimum(3);
    sizeSlider.setValue(3);
    sizeSlider.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        sizeSliderMouseReleased(evt);
      }
    });
    sizeSlider.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        sizeSliderStateChanged(evt);
      }
    });

    wLabel2.setText("0.33333");

    wSlider.setMaximum(99999);
    wSlider.setValue(33333);
    wSlider.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        wSliderMouseReleased(evt);
      }
    });
    wSlider.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        wSliderStateChanged(evt);
      }
    });

    probabilisticPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Probabilistic"));
    p1Label.setText("p1");

    p2Label.setText("p2");

    p3Label.setText("p3");

    jLabel4.setText("p4");

    p1ValueLabel.setText("n/a");

    p2ValueLabel.setText("n/a");

    p3ValueLabel.setText("n/a");

    p4ValueLabel.setText("n/a");

    org.jdesktop.layout.GroupLayout probabilisticPanelLayout = new org.jdesktop.layout.GroupLayout(probabilisticPanel);
    probabilisticPanel.setLayout(probabilisticPanelLayout);
    probabilisticPanelLayout.setHorizontalGroup(
      probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(probabilisticPanelLayout.createSequentialGroup()
        .add(p1Label)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
        .add(p1ValueLabel))
      .add(probabilisticPanelLayout.createSequentialGroup()
        .add(jLabel4)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
        .add(p4ValueLabel))
      .add(probabilisticPanelLayout.createSequentialGroup()
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
          .add(p2Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(p3Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, p3ValueLabel)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, p2ValueLabel)))
    );
    probabilisticPanelLayout.setVerticalGroup(
      probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(probabilisticPanelLayout.createSequentialGroup()
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(p1Label)
          .add(p1ValueLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(p2ValueLabel)
          .add(p2Label))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(p3Label)
          .add(p3ValueLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(probabilisticPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(p4ValueLabel)))
    );

    org.jdesktop.layout.GroupLayout variablePanelLayout = new org.jdesktop.layout.GroupLayout(variablePanel);
    variablePanel.setLayout(variablePanelLayout);
    variablePanelLayout.setHorizontalGroup(
      variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, variablePanelLayout.createSequentialGroup()
        .add(variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(wLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
          .add(sizeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
        .add(34, 34, 34)
        .add(variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(sizeLabel2)
          .add(wLabel2)))
      .add(neighbourPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .add(playerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .add(sizeSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, wSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
      .add(probabilisticPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    variablePanelLayout.setVerticalGroup(
      variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(variablePanelLayout.createSequentialGroup()
        .add(variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(sizeLabel)
          .add(sizeLabel2))
        .add(4, 4, 4)
        .add(sizeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(variablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(wLabel)
          .add(wLabel2))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(wSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(4, 4, 4)
        .add(neighbourPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(playerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(probabilisticPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    runButton.setText("Run");
    runButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        runButtonActionPerformed(evt);
      }
    });

    speedLabel.setText("Execution Speed:");

    speedSlider.setMaximum(300);
    speedSlider.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        speedSliderMouseReleased(evt);
      }
    });
    speedSlider.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        speedSliderStateChanged(evt);
      }
    });

    speedLabel2.setText("0.5 secs");

    resultsLabel.setText("Collect Results Every " + resultInterval + " Generations");
    resultsLabel.setText("Collect Results Every 50 Generations");

    resultsCheckBox.setSelected(collectResults);
    resultsCheckBox.setText("Collect Results");
    resultsCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    resultsCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
    resultsCheckBox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        resultsCheckBoxActionPerformed(evt);
      }
    });

    resultsSlider.setMaximum(500);
    resultsSlider.setMinimum(1);
    resultsSlider.setValue(resultInterval);
    resultsSlider.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        resultsSliderMouseReleased(evt);
      }
    });
    resultsSlider.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        resultsSliderStateChanged(evt);
      }
    });

    file.setText("File");
    newGame.setText("New Game");
    newGame.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        newGameActionPerformed(evt);
      }
    });

    file.add(newGame);

    quit.setText("Quit");
    quit.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        quitActionPerformed(evt);
      }
    });

    file.add(quit);

    jMenuBar1.add(file);

    help.setText("Help");
    help.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        helpActionPerformed(evt);
      }
    });

    about.setText("About");
    about.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        aboutActionPerformed(evt);
      }
    });

    help.add(about);

    jMenuBar1.add(help);

    setJMenuBar(jMenuBar1);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(territoryGrid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(generationLabel))
            .add(27, 27, 27))
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, resultsSlider, 0, 0, Short.MAX_VALUE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, resultsLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(resultsCheckBox))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, speedSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(speedLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
            .add(speedLabel2))
          .add(org.jdesktop.layout.GroupLayout.TRAILING, runButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, step, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
          .add(variablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(generationLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(territoryGrid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(variablePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(step)
          .add(resultsCheckBox))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(runButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(speedLabel2)
              .add(speedLabel))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(speedSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(resultsLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(resultsSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void resultsSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_resultsSliderStateChanged
  {//GEN-HEADEREND:event_resultsSliderStateChanged
    resultsLabel.setText("Collect Results Every " + resultsSlider.getValue() + " Generations");
  }//GEN-LAST:event_resultsSliderStateChanged

  private void resultsCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resultsCheckBoxActionPerformed
  {//GEN-HEADEREND:event_resultsCheckBoxActionPerformed
    collectResults = resultsCheckBox.isSelected();
  }//GEN-LAST:event_resultsCheckBoxActionPerformed

  private void resultsSliderMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_resultsSliderMouseReleased
  {//GEN-HEADEREND:event_resultsSliderMouseReleased
    resultInterval = resultsSlider.getValue();
    resultsLabel.setText("Collect Results Every " + resultInterval + " Generations");
  }//GEN-LAST:event_resultsSliderMouseReleased

  private void speedSliderMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_speedSliderMouseReleased
  {//GEN-HEADEREND:event_speedSliderMouseReleased
    runSpeed = speedSlider.getValue() * 10;
  }//GEN-LAST:event_speedSliderMouseReleased

  private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_speedSliderStateChanged
  {//GEN-HEADEREND:event_speedSliderStateChanged
    // Set the speedLabel2 to be the slider value.
    speedLabel2.setText(((double)speedSlider.getValue()/100)+ " secs");
    
    runSpeed = speedSlider.getValue() * 10;
  }//GEN-LAST:event_speedSliderStateChanged

  private void wSliderMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_wSliderMouseReleased
  {//GEN-HEADEREND:event_wSliderMouseReleased
    // Simply set w.
    Game.setW((double) wSlider.getValue()/100000);
  }//GEN-LAST:event_wSliderMouseReleased

  private void wSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_wSliderStateChanged
  {//GEN-HEADEREND:event_wSliderStateChanged
    // Set the wLabel2 to be the slider value.
    wLabel2.setText("" + ((double)wSlider.getValue()/100000));
  }//GEN-LAST:event_wSliderStateChanged

  private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sizeSliderStateChanged
  {//GEN-HEADEREND:event_sizeSliderStateChanged
    // Set the sizeLabel2 to be the slider value.
    sizeLabel2.setText("" + sizeSlider.getValue());
  }//GEN-LAST:event_sizeSliderStateChanged

  private void sizeSliderMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sizeSliderMouseReleased
  {//GEN-HEADEREND:event_sizeSliderMouseReleased
    // If running, stop execution.
    if(timer != null)
    {
      running = false;
      timer.cancel();
      runButton.setText("Run");
    } // if
    
    int sze = sizeSlider.getValue();
    size = sze;
    
    // Set the territory size.
    territoryGrid.setSize(size);
    
    // Reset the generation count.
    generationLabel.setText("Generation 0");
    generation = 0;
    
    // Clear the info.
    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
    stratCombo.setEnabled(false);
    selectedPlayer = null;
    playerPayoffField.setText("");
    
    // Repack because the size of the window has changed.
    pack();
  }//GEN-LAST:event_sizeSliderMouseReleased

  private void eightNeighRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eightNeighRadioButtonActionPerformed
  {//GEN-HEADEREND:event_eightNeighRadioButtonActionPerformed
    // TODO add your handling code here:
    if(fourNeighbours)
    {
      fourNeighbours = false;
      territoryGrid.setNeighbours(fourNeighbours);
    } // if
  }//GEN-LAST:event_eightNeighRadioButtonActionPerformed

  private void fourNeighRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fourNeighRadioButtonActionPerformed
  {//GEN-HEADEREND:event_fourNeighRadioButtonActionPerformed
    // TODO add your handling code here:
    if(!fourNeighbours)
    {
      fourNeighbours = true;
      territoryGrid.setNeighbours(fourNeighbours);
    } // if
  }//GEN-LAST:event_fourNeighRadioButtonActionPerformed

  // Store variables to handling running and pausing.
  private boolean running = false;
  private java.util.Timer timer;
  int runSpeed = 500;
  
  // Handle the running and pausing with Timers and delayed TimerTasks.
  private void runButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runButtonActionPerformed
  {//GEN-HEADEREND:event_runButtonActionPerformed
    running = !running;
    
    if(running)
    {
      runButton.setText("Pause");
      
      territoryGrid.setEnabled(false);
      
      timer = new java.util.Timer();
      
      // Collect results.
      if(collectResults && generation % resultInterval == 0)
        collectResults();
      
      stepThrough();      
    } // if
    else
    {
      runButton.setText("Run");
      timer.cancel();
      territoryGrid.setEnabled(true);
    } // else
  }//GEN-LAST:event_runButtonActionPerformed

  private void stratComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stratComboActionPerformed
  {//GEN-HEADEREND:event_stratComboActionPerformed
    // TODO add your handling code here:
    if(selectedPlayer != null)
    {
      Strategy strat = (Strategy)stratCombo.getSelectedItem();
      if(strat.toString().equals("Probabilistic"))
        selectedPlayer.setPlayersStrategy(new Probabilistic());
      else
        selectedPlayer.setPlayersStrategy(strat);
    } // if
    
    territoryGrid.updateColour(row, column);
  }//GEN-LAST:event_stratComboActionPerformed

  private void quitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitActionPerformed
  {//GEN-HEADEREND:event_quitActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_quitActionPerformed

  private void aboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutActionPerformed
  {//GEN-HEADEREND:event_aboutActionPerformed
    // TODO add your handling code here:
    new About().setVisible(true);
  }//GEN-LAST:event_aboutActionPerformed

  private void newGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newGameActionPerformed
  {//GEN-HEADEREND:event_newGameActionPerformed
    // If running, stop execution.
    if(timer != null)
    {
      running = false;
      timer.cancel();
      runButton.setText("Run");
    } // if
    
    // Set the territory size.
    territoryGrid.setSize(size);
    
    // Reset the generation count.
    generationLabel.setText("Generation 0");
    generation = 0;
    
    // Clear the info.
    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
    stratCombo.setEnabled(false);
    selectedPlayer = null;
    playerPayoffField.setText("");
    p1ValueLabel.setText("n/a");
    p2ValueLabel.setText("n/a");
    p3ValueLabel.setText("n/a");
    p4ValueLabel.setText("n/a");
    
    // Repack because the size of the window has changed.
    pack();
  }//GEN-LAST:event_newGameActionPerformed

  private void helpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_helpActionPerformed
  {//GEN-HEADEREND:event_helpActionPerformed
// TODO add your handling code here:
  }//GEN-LAST:event_helpActionPerformed

  private void stepActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stepActionPerformed
  {//GEN-HEADEREND:event_stepActionPerformed
    // Collect results.
    if(collectResults && generation % resultInterval == 0)
      collectResults();
    
    territoryGrid.step();
    generation++;
    generationLabel.setText("Generation " + generation);
    
    // Clear the info.
    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
    stratCombo.setEnabled(false);
    selectedPlayer = null;
    playerPayoffField.setText("");
    p1ValueLabel.setText("n/a");
    p2ValueLabel.setText("n/a");
    p3ValueLabel.setText("n/a");
    p4ValueLabel.setText("n/a");
  }//GEN-LAST:event_stepActionPerformed
  
  // Method to run through one step of execution.
  private void stepThrough()
  {
    territoryGrid.step();
    generation++;
    generationLabel.setText("Generation " + generation);
    
    // Clear the info.
    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
    stratCombo.setEnabled(false);
    selectedPlayer = null;
    playerPayoffField.setText("");
    p1ValueLabel.setText("n/a");
    p2ValueLabel.setText("n/a");
    p3ValueLabel.setText("n/a");
    p4ValueLabel.setText("n/a");
    
    timer.schedule(new java.util.TimerTask()
    {
      public void run()
      {
        // Collect results.
        if(collectResults && generation % resultInterval == 0)
          collectResults();
        
        stepThrough();
      } // run
    }, runSpeed);
  } // stepThrough
  
  // Method to collect the results.
  private void collectResults()
  {
    // Create an image of the grid.
    createImage(territoryGrid, "gen"+generation+".png");
    
    // Sort out the histograms.
    // p1 first.
    HistogramDataset series = new HistogramDataset();
    double [] pValues = territoryGrid.getP1Values();
    
    series.addSeries("key", pValues, 10);
    
    JFreeChart theChart = ChartFactory.createHistogram("p1 Values for Generation " + generation,
       "p1 Values", "Frequency", series, PlotOrientation.VERTICAL, false, false, false);
    
    ChartPanel p = new ChartPanel(theChart);
    
    JFrame frame = new JFrame();
    frame.setBounds(0,0,WIDTH,HEIGHT);
    frame.getContentPane().add(p);
    frame.pack();
    frame.setVisible(false);
    // Export it to an image.
    createImage(p, "p1Gen"+generation+".png");
    
    // p2
    series = new HistogramDataset();
    pValues = territoryGrid.getP2Values();
    
    series.addSeries("key", pValues, 10);
    
    theChart = ChartFactory.createHistogram("p2 Values for Generation " + generation,
       "p2 Values", "Frequency", series, PlotOrientation.VERTICAL, false, false, false);
    
    p = new ChartPanel(theChart);
    
    frame = new JFrame();
    frame.setBounds(0,0,WIDTH,HEIGHT);
    frame.getContentPane().add(p);
    frame.pack();
    frame.setVisible(false);
    // Export it to an image.
    createImage(p, "p2Gen"+generation+".png");
    
    // p3
    series = new HistogramDataset();
    pValues = territoryGrid.getP3Values();
    
    series.addSeries("key", pValues, 10);
    
    theChart = ChartFactory.createHistogram("p3 Values for Generation " + generation,
       "p3 Values", "Frequency", series, PlotOrientation.VERTICAL, false, false, false);
    
    p = new ChartPanel(theChart);
    
    frame = new JFrame();
    frame.setBounds(0,0,WIDTH,HEIGHT);
    frame.getContentPane().add(p);
    frame.pack();
    frame.setVisible(false);
    // Export it to an image.
    createImage(p, "p3Gen"+generation+".png");
    
    // p4
    series = new HistogramDataset();
    pValues = territoryGrid.getP4Values();
    
    series.addSeries("key", pValues, 10);
    
    theChart = ChartFactory.createHistogram("p4 Values for Generation " + generation,
       "p4 Values", "Frequency", series, PlotOrientation.VERTICAL, false, false, false);
    
    p = new ChartPanel(theChart);
    
    frame = new JFrame();
    frame.setBounds(0,0,WIDTH,HEIGHT);
    frame.getContentPane().add(p);
    frame.pack();
    frame.setVisible(false);
    // Export it to an image.
    createImage(p, "p4Gen"+generation+".png");
    
    // Get the ranked HashMap of Strategies.
    HashMap<Probabilistic, Integer> strats = territoryGrid.getRankedProbabilistic();
    
    // Remove the values.
    /*ArrayList<Integer> stratQuant = new ArrayList<Integer>(strats.values());
    Collections.sort(stratQuant);*/
    
    HashSet<Entry<Probabilistic, Integer>> stratSet = new HashSet<Entry<Probabilistic, Integer>>(strats.entrySet());
    Iterator<Entry<Probabilistic, Integer>> iterator = stratSet.iterator();
    // Keep arrays of both the quantities and the actual Strategy.
    probs = new Probabilistic[stratSet.size()];
    quants = new int[stratSet.size()];
    int i = 0;
    while(iterator.hasNext())
    {
      Entry<Probabilistic, Integer> entry = iterator.next();
      quants[i] = entry.getValue();
      probs[i] = entry.getKey();
      i++;
    } // while
    
    sortTopTen(0, quants.length - 1);
    
    int length;
    if(quants.length < 10)
      length = quants.length;
    else
      length = 10;
    
    try
    {
      PrintWriter out = new PrintWriter(new FileWriter("topTenGen" + generation + ".txt"));
      
      int j = 1;
      for(i = length - 1; i >= 0; i--, j++)
        out.println(j + ". p1: " + probs[i].getP1() +
           "\tp2: " + probs[i].getP2() +
           "\t\tp3: " + probs[i].getP3() +
           "\t\tp4: " + probs[i].getP4() + "\tOccurrences: " + quants[i]);
      
      out.close();
    } // try
    catch (IOException e)
    {
      System.err.println(e);
    } // catch
  } // collectResults
  
  // Method to sort the Probabilistic quanities and the Probabilistic's also.
  private void sortTopTen(int low, int high)
  {
    if(low == high)  
      return;
    
    // Split the array.
    int length = high - low + 1; 
    int middle = (low + high) / 2;
    
    // Call the method on the left list.
    sortTopTen(low, middle);
    // Call the method on the right list.
    sortTopTen(middle + 1, high);
    
    // Merge the lists.
    int [] temp = new int[length];
    Probabilistic [] temp2 = new Probabilistic[length];
    
    for(int i = 0; i < length; i++)
    {
      temp[i] = quants[low + i];
      temp2[i] = probs[low + i];
    } // for
    
    // Order properly.
    int m1 = 0;  
    int m2 = middle - low + 1; 
    for(int i = 0; i < length; i++)
    {
      if(m2 <= high - low)
      {
        if(m1 <= middle - low)
	{
          if(temp[m1] > temp[m2])
	  {
            quants[i + low] = temp[m2];
            probs[i + low] = temp2[m2++];
	  } // if
          else
	  {
            quants[i + low] = temp[m1];
            probs[i + low] = temp2[m1++];
	  } // else
	} // if
        else
	{
          quants[i + low] = temp[m2];
          probs[i + low] = temp2[m2];
	} // else
      } // if
      else
      {
        quants[i + low] = temp[m1];
        probs[i + low] = temp2[m1++];
      } // else
    } // for
  } // sortTopTen
  
  // Method to create an image from a JComponent.
  private void createImage(JComponent comp, String fname)
  {
    Dimension d = comp.getPreferredSize();
    Rectangle region = new Rectangle(0, 0, d.width, d.height);
    
    boolean opaqueValue = comp.isOpaque();
    comp.setOpaque(true);
    BufferedImage image = new BufferedImage(region.width, region.height,
                                            BufferedImage.TYPE_INT_RGB);
    Graphics2D g2d = image.createGraphics();
    g2d.setClip(region);
    comp.paint(g2d);
    g2d.dispose();
    comp.setOpaque(opaqueValue);
    
    try
    {
      ImageIO.write(image, "png", new File(fname));
    } catch(IOException e){}
  } // createImage
  
  /**
   * Get the Player for which the button has been pressed in a 
   * territory. In this instance, update its information.
   *
   * @param plyr The Player
   * @param i The Player's row
   * @param j The Player's column
   */
  public void processButton(Player plyr, int i, int j)
  {
    // Update all the info.
    selectedPlayer = plyr;
    row = i;
    column = j;
    playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player " + i + ", " + j));
    stratCombo.setEnabled(true);
    stratCombo.setSelectedItem(selectedPlayer.getPlayersStrategy());
    playerPayoffField.setText("" + plyr.getPayoff());
    
    if(plyr.getPlayersStrategy() instanceof Probabilistic)
    {
      p1ValueLabel.setText("" + ((Probabilistic)plyr.getPlayersStrategy()).getP1());
      p2ValueLabel.setText("" + ((Probabilistic)plyr.getPlayersStrategy()).getP2());
      p3ValueLabel.setText("" + ((Probabilistic)plyr.getPlayersStrategy()).getP3());
      p4ValueLabel.setText("" + ((Probabilistic)plyr.getPlayersStrategy()).getP4());
    } // if
  } // processButton
  
    /**
     * Simply create and display the Evolution GUI.
     *
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
        public void run()
        {              
          new EvolutionGUI().setVisible(true);
        } // run
      });
    } // main
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem about;
  private javax.swing.JRadioButton eightNeighRadioButton;
  private javax.swing.JMenu file;
  private javax.swing.JRadioButton fourNeighRadioButton;
  private javax.swing.JLabel generationLabel;
  private javax.swing.JMenu help;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.ButtonGroup neighbourButtonGroup;
  private javax.swing.JPanel neighbourPanel;
  private javax.swing.JMenuItem newGame;
  private javax.swing.JLabel p1Label;
  private javax.swing.JLabel p1ValueLabel;
  private javax.swing.JLabel p2Label;
  private javax.swing.JLabel p2ValueLabel;
  private javax.swing.JLabel p3Label;
  private javax.swing.JLabel p3ValueLabel;
  private javax.swing.JLabel p4ValueLabel;
  private javax.swing.JPanel playerPanel;
  private javax.swing.JLabel playerPayoff;
  private javax.swing.JTextField playerPayoffField;
  private javax.swing.JPanel probabilisticPanel;
  private javax.swing.JMenuItem quit;
  private javax.swing.JCheckBox resultsCheckBox;
  private javax.swing.JLabel resultsLabel;
  private javax.swing.JSlider resultsSlider;
  private javax.swing.JButton runButton;
  private javax.swing.JLabel sizeLabel;
  private javax.swing.JLabel sizeLabel2;
  private javax.swing.JSlider sizeSlider;
  private javax.swing.JLabel speedLabel;
  private javax.swing.JLabel speedLabel2;
  private javax.swing.JSlider speedSlider;
  private javax.swing.JButton step;
  private javax.swing.JComboBox stratCombo;
  private javax.swing.JLabel stratLabel;
  private TerritoryGrid territoryGrid;
  private javax.swing.JPanel variablePanel;
  private javax.swing.JLabel wLabel;
  private javax.swing.JLabel wLabel2;
  private javax.swing.JSlider wSlider;
  // End of variables declaration//GEN-END:variables
    
}
